services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qc-front-v2
    restart: always
    ports:
      - '3000:3000'
    # env_file:
    #   - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge